<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-13T17:00:00 BST" name="Suite" finished-at="2023-09-13T17:00:54 BST" duration-ms="54365">
    <groups>
      <group name="regression">
        <method signature="FillForm_Validation.FillForm_NegativeTest()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" name="FillForm_NegativeTest" class="testcases.FillForm_Validation"/>
        <method signature="FillForm_Validation.FillForm_PositiveTest()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" name="FillForm_PositiveTest" class="testcases.FillForm_Validation"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2023-09-13T17:00:00 BST" name="End To End Framework Test" finished-at="2023-09-13T17:00:00 BST" duration-ms="15">
    </test> <!-- End To End Framework Test -->
    <test started-at="2023-09-13T17:00:00 BST" name="Error Validation Test" finished-at="2023-09-13T17:00:54 BST" duration-ms="53962">
      <class name="testcases.FillForm_Validation">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" started-at="2023-09-13T17:00:00 BST" name="ConfigureAppium" finished-at="2023-09-13T17:00:10 BST" duration-ms="9962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method signature="FillForm_NegativeTest()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" started-at="2023-09-13T17:00:10 BST" name="FillForm_NegativeTest" finished-at="2023-09-13T17:00:27 BST" duration-ms="16603" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter your name1] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter your name1] but found [Please enter your name]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.FillForm_Validation.FillForm_NegativeTest(FillForm_Validation.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_NegativeTest -->
        <test-method signature="FillForm_PositiveTest()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" started-at="2023-09-13T17:00:28 BST" name="FillForm_PositiveTest" finished-at="2023-09-13T17:00:54 BST" duration-ms="25616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_PositiveTest -->
        <test-method is-config="true" signature="teardownAppium()[pri:0, instance:testcases.FillForm_Validation@4879dfad]" started-at="2023-09-13T17:00:54 BST" name="teardownAppium" finished-at="2023-09-13T17:00:54 BST" duration-ms="518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownAppium -->
      </class> <!-- testcases.FillForm_Validation -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
